# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "http://vidaeficiente.es/"
DefaultContentLanguage  = "es"
title                   = "VidaEficiente"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = "vidaeficiente-es"
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []

[markup.goldmark.renderer]
  unsafe                = true

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = false

  [params.meta]
    description         = "Un diario sobre el viaje hacia un mejor yo"
    author              = "David"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.meta.en]
    description         = "travelling"


  [params.header]
    navbarTitle         = "VidaEficiente"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = true

  [params.intro]
    header                = "VidaEficiente"
    paragraph             = "Un diario sobre el viaje hacia un mejor yo"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

  [params.intro.pic]
      src                 = "img/main/logo.png"
      shape               = "circle"
      width               = "155"
      alt                 = "David"

  #About lateral. configurar.
  [params.sidebar]
    minibio             = false
    about               = "En este blog comparto, a modo de diario personal, los recursos, trucos y tips que realmente me han funcionado para generar buenos hábitos y hacerme más eficiente"
    postAmount          = 5
    categories          = true
    categoriesByCount   = true


  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = ""
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = "" 
    theme               = "github-light"

## Esto es para habilitar los comentarios con staticman.
## Leer https://themes.gohugo.io/hugo-future-imperfect-slim/
## De momento usamos Disqus

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

# iconos : https://www.angularjswiki.com/fontawesome/
[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Sobre mí"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categorias"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 4

  [[menu.main]]
    name              = "Tags"
    identifier        = "tags"
    url               = "/tags/"
    pre               = "<i class='fas fa-tags'></i>"
    weight            = 5

  [[menu.main]]
    name              = "Libros"
    identifier        = "books"
    url               = "/books/booklist"
    pre               = "<i class='fas fa-book-reader'></i>"
    weight            = 6

#  [[menu.main]]
#    name              = "Contacto"
#    identifier        = "contact"
#    url               = "/contact/"
#    pre               = "<i class='far fa-envelope'></i>"
#    weight            = 7


[Languages]

  [Languages.es]
    LanguageCode        = "es"
    LanguageName        = "Español"
    weight              = 1

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    title               = "VidaEficiente"
    description         = "A journal about the travel to a better me"
    about               = "Sobre mí"
    weight              = 2


  [Languages.en.params.intro]
    header                = "VidaEficiente"
    paragraph             = "A journal about the travel to a better me"
    about                 = "About me"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = false
    alwaysOnHomepage      = false

  [Languages.en.params.intro.pic]
      src                 = "img/main/logo.png"
      shape               = "circle"
      width               = "155"
      alt                 = "David"

  [Languages.en.params.sidebar]
    minibio             = false
    about               = "In this blog I share those tricks, tips and resources that have really helped me in order to generate better habits and become more efficient."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true



    [[Languages.en.menu.main]]
      name              = "Home"
      identifier        = "home"
      url               = "/"
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.en.menu.main]]
      name              = "About"
      identifier        = "about"
      url               = "/about/"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.en.menu.main]]
      name              = "Blog"
      identifier        = "blog"
      url               = "/blog/"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    [[Languages.en.menu.main]]
      name              = "Categories"
      identifier        = "categories"
      url               = "/categories/"
      pre               = "<i class='fas fa-sitemap'></i>"
      weight            = 4

    [[Languages.en.menu.main]]
      name              = "Tags"
      identifier        = "tags"
      url               = "/tags/"
      pre               = "<i class='fas fa-tags'></i>"
      weight            = 5

    [[Languages.en.menu.main]]
      name              = "Books"
      identifier        = "books"
      url               = "/books/booklist"
      pre               = "<i class='fas fa-book-reader'></i>"
      weight            = 6

#    [[Languages.en.menu.main]]
#      name              = "Contact"
#      identifier        = "contact"
#      url               = "/contact/"
#      pre               = "<i class='far fa-envelope'></i>"
#      weight            = 7



[social]
  # Coding Communities
  github                = ""
  gitlab                = ""
  stackoverflow         = "" # User Number
  bitbucket             = ""
  jsfiddle              = ""
  codepen               = ""

  # Visual Art Communities
  deviantart            = ""
  flickr                = ""
  behance               = ""
  dribbble              = ""

  # Publishing Communities
  wordpress             = ""
  medium                = ""

  # Professional/Business Oriented Communities
  linkedin              = ""
  linkedin_company      = ""
  foursquare            = ""
  xing                  = ""
  slideshare            = ""

  # Social Networks
  facebook              = ""
  googleplus            = ""
  reddit                = ""
  quora                 = ""
  youtube               = ""
  vimeo                 = ""
  whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat              = ""
    qq                  = "" # User ID Number
  instagram             = ""
  tumblr                = ""
  twitter               = "@vidaeficiente"
  strava                = ""
  skype                 = ""
  snapchat              = ""
  pinterest             = ""
  telegram              = ""
  vine                  = ""
  googlescholar         = ""
  orcid                 = ""
  researchgate          = ""
  keybase               = ""
  mastodon              = ""

  # Email
  email                 = "vidaeficiente.es@gmail.com"
